#pragma once

#define TEXT_COLOR_RED L"\x1b[31m"
#define TEXT_COLOR_GREEN L"\x1b[32m"
#define TEXT_COLOR_YELLOW L"\x1b[33m"
#define TEXT_COLOR_BLUE L"\x1b[34m"
#define TEXT_COLOR_MAGENTA L"\x1b[35m"
#define TEXT_COLOR_CYAN L"\x1b[36m"
#define TEXT_COLOR_RESET L"\x1b[0m"
#define TEXT_COLOR_BRIGHT_BLACK L"\x1b[30;1m"
#define TEXT_COLOR_BRIGHT_RED L"\x1b[31;1m"
#define TEXT_COLOR_BRIGHT_GREEN L"\x1b[32;1m"
#define TEXT_COLOR_BRIGHT_YELLOW L"\x1b[33;1m"
#define TEXT_COLOR_BRIGHT_BLUE L"\x1b[34;1m"
#define TEXT_COLOR_BRIGHT_MAGENTA L"\x1b[35;1m"
#define TEXT_COLOR_BRIGHT_CYAN L"\x1b[36;1m"
#define TEXT_COLOR_BRIGHT_WHITE L"\x1b[37;1m"

#define TEXT_STYLE_BOLD L"\x1b[1m"
#define TEXT_STYLE_UNDERLINE L"\x1b[4m"
#define TEXT_STYLE_REVERSED L"\x1b[7m"

#define BACKGROUND_COLOR_BLACK L"\x1b[40m"
#define BACKGROUND_COLOR_RED L"\x1b[41m"
#define BACKGROUND_COLOR_GREEN L"\x1b[42m"
#define BACKGROUND_COLOR_YELLOW L"\x1b[43m"
#define BACKGROUND_COLOR_BLUE L"\x1b[44m"
#define BACKGROUND_COLOR_MAGENTA L"\x1b[45m"
#define BACKGROUND_COLOR_CYAN L"\x1b[46m"
#define BACKGROUND_COLOR_WHITE L"\x1b[47m"
#define BACKGROUND_COLOR_RESET L"\x1b[0m"

#define BACKGROUND_COLOR_BRIGHT_BLACK L"\x1b[40;1m"
#define BACKGROUND_COLOR_BRIGHT_RED L"\x1b[41;1m"
#define BACKGROUND_COLOR_BRIGHT_GREEB L"\x1b[42;1m"
#define BACKGROUND_COLOR_BRIGHT_YELLOW L"\x1b[43;1m"
#define BACKGROUND_COLOR_BRIGHT_BLUE L"\x1b[44;1m"
#define BACKGROUND_COLOR_BRIGHT_MAGENTA L"\x1b[45;1m"
#define BACKGROUND_COLOR_BRIGHT_CYAN L"\x1b[46;1m"
#define BACKGROUND_COLOR_BRIGHT_WHITE L"\x1b[47;1m"

#define MAX_BUF_W 500
#define MAX_BUF_H 500

#define DEFAULT_WIN_BORDER L"=-||++++"